### PR TITLE
fix(auth): anonymous user check in JWTAuthentication middleware

### PR DESCRIPTION
**Pull request by nikomakela**
This pull rquest should fix an issue that prevents anonymous users to use the public GraphQL API. This PR is an alternative for https://github.com/City-of-Helsinki/kukkuu/pull/423.

KK-1224.

Copied implementations from [graphql_jwt](https://github.com/flavors/django-graphql-jwt):

1. Need for authentication:
https://github.com/flavors/django-graphql-jwt/blob/main/graphql_jwt/middleware.py
2. Get authorization header:
https://github.com/flavors/django-graphql-jwt/blob/main/graphql_jwt/utils.py

### CODE REVIEW

**Comment by terovirtanen** [comment]
**KUKKUU-API branch is deployed to platta: https://kukkuu-pr422.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-pr422.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by karisal-anders** [comment]
I approved the alternative version https://github.com/City-of-Helsinki/kukkuu/pull/423 as IMO that is the technically the better choice for maintenance because of less copy paste from other libraries. If you want, we can discuss the pros and cons of these PRs live.

**Comment by nikomakela** [comment]
> I approved the alternative version #423 as IMO that is technically the better choice for maintenance because of less copy paste from other libraries. If you want, we can discuss the pros and cons of these PRs live.

I think it has even been the main plan to not have a dependency to some 3rd party library, but I would say that the one that we now added, is so well known and used, that it is good to have it. I personally like the #423 more too, since it uses the `authentication_backend` configuration and some well tested 3rd party library for graphene auth check middleware. This one just had less changes and followed the idea of "don't bring new dependencies".

The #423 is now merged, so closing this!

**Pull request closed without merging**
