### PR TITLE
fix: rename kukkuu_mailer to kukkuu_mailer_admin

### PR DESCRIPTION
**Pull request by nikomakela**
KK-1172.
The name might be bad for CI (or so it seems).

### CODE REVIEW

**Review by karisal-anders — APPROVED** [review]

**Comment by terovirtanen** [comment]
**KUKKUU-API branch is deployed to platta: https://kukkuu-pr378.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by karisal-anders** [comment]
It was probably the missing `__init__.py`, not the name.

**Comment by terovirtanen** [comment]
**KUKKUU-API branch is deployed to platta: https://kukkuu-pr378.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-pr378.api.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
