### PR TITLE
ci: remove create_superuser env-variable

### PR DESCRIPTION
**Pull request by nikomakela**
KK-1167

### CODE REVIEW

**Comment by terovirtanen** [comment]
**KUKKUU-API branch is deployed to platta: https://kukkuu-pr365.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-pr365.api.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-pr365.api.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-pr365.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by nikomakela** [comment]
The [pipeline changes](https://dev.azure.com/City-of-Helsinki/kukkuu/_git/kukkuu-pipelines/pullrequest/8633) are already merged to master, so they are active -- See the green result! :)

**Review by karisal-anders — APPROVED** [review]

**Pull request merged**
