### PR TITLE
Child update mutation for birthdate should be ignored

### PR DESCRIPTION
**Pull request by nikomakela**
KK-428.

The updating of the child's birthdate field should not be possible anymore. This pull request should not require any changes from the client, since it only deprecates the birthdate field and ignores it while updating or validating the child instance (and it's input).

NOTE: There is an [alternative PR](https://github.com/City-of-Helsinki/kukkuu/pull/334) for this that actually removes the field from the child update mutation input.

NOTE: https://github.com/City-of-Helsinki/kukkuu/pull/336 and https://github.com/City-of-Helsinki/kukkuu/pull/336 will force some API changes anyway, so therefore the https://github.com/City-of-Helsinki/kukkuu/pull/334 is remomended choice.

### CODE REVIEW

**Comment by terovirtanen** [comment]
**KUKKUU-API branch is deployed to platta: https://kukkuu-pr333.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-pr333.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by nikomakela** [comment]
This will somewhat conflict with https://github.com/City-of-Helsinki/kukkuu/pull/336 and https://github.com/City-of-Helsinki/kukkuu/pull/337.

**Review by karisal-anders — COMMENTED** [review]
I vote for PR #334 i.e. for removing the input rather than deprecating it. Leaves less technical debt to maintain.

**Pull request closed without merging**
