### PR TITLE
fix: fork django-ilmoitin to generate migrations for Django 4.2 compatibility

### PR DESCRIPTION
**Pull request by nikomakela**
Generated migrations using `python manage.py makemigrations` to address
compatibility issues with Django 4.2 in the `django-ilmoitin` package.

The following models were affected:
- NotificationTemplate: Altered `admins_to_notify` field.
- NotificationTemplateTranslation: Altered `id` field.

### CODE REVIEW

**Comment by nikomakela** [comment]
Before applying these changes, we should contact the developers who maintain the django-ilmoitin and ask if they could just publish a new version with the related migrations.

NOTE: I also tested that when using Django 3.2, there is still one migration to be applied.

We could also just provide them a new pull request that contains the new migration, since they seem to have already tried to support Django 4: https://github.com/City-of-Helsinki/django-ilmoitin/pull/34. It seems like they have just forgot to ran the `python manage.py makemigrations`.

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-pr425.api.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Review by karisal-anders — APPROVED** [review]
Otherwise looks like an ok compromise given the situation, but I think it'd be good to give an exact tag/release/commit hash in the README.md as a point of reference against which to compare the forked django-ilmoitin. So someone looking at the code knows that ok, they took e.g. v0.7.0 of django-ilmoitin and then added what's mentioned in "Key Modifications" onto that. Please could you add that and then this'd be ok to merge IMHO.

Adding a comment to `requirements.in` might be prudent too, although not strictly necessary, e.g.
```
django-ilmoitin  # NOTE: This is overridden by local fork! See README.md
```
or something else.

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-pr425.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by nikomakela** [comment]
> The [browser tests](https://dev.azure.com/City-of-Helsinki/kukkuu/_build/results?buildId=203256&view=logs&jobId=876554bf-daa7-536c-994f-a1a921dd9eb5&j=876554bf-daa7-536c-994f-a1a921dd9eb5&t=c96cbdcd-9d75-5037-ceff-84d40df94aa4) are failing for some reason

Not anymore after a rerun. Strange that there was a hickup like that because the API browser tests has been quite reliable.

**Comment by nikomakela** [comment]
I created to PR to django-ilmoitin: 
- Django 3.2: https://github.com/City-of-Helsinki/django-ilmoitin/pull/41
- Django 4.2: https://github.com/City-of-Helsinki/django-ilmoitin/pull/42

**Comment by nikomakela** [comment]
Closing this, since the https://github.com/City-of-Helsinki/django-ilmoitin/pull/42 got merged and will be released soonish.

**Pull request closed without merging**
