### PR TITLE
KK-1184 | feat: test auth change notifications command's query count

### PR DESCRIPTION
**Pull request by karisal-anders**
### feat: test auth change notifications command's query count

refs KK-1184

## Related

[KK-1184](https://helsinkisolutionoffice.atlassian.net/browse/KK-1184)

[KK-1184]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by karisal-anders** [comment]
@nikomakela If you approve this PR you can just merge this right away, thank you!

**Comment by terovirtanen** [comment]
**KUKKUU-API branch is deployed to platta: https://kukkuu-pr388.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-pr388.api.dev.hel.ninja :laughing::tada::tada::tada:

**Review by nikomakela — APPROVED** [review]
Well done!

**Pull request merged**
